### ISSUE TITLE
CSS Not Loading

### ISSUE THREAD

**Issue by Hybridx24** [wojtekmaj/react-daterange-picker#1]
First off, AMAZING project! I love all of your work.

The only issue I seem to be having is with this component - it seems as if the CSS is not loading for some reason. The demo link in the readme also seems to be down, so I can't see what it's even supposed to look like. Any thoughts?

**Comment by wojtekmaj** [comment]
Hi,
Contrary to what README says, this is actually not yet published project :( It's just ready to be published any minute. Should you want to use it, you would need to use GitHub link in your package.json.

**Comment by wojtekmaj** [comment]
What you're seeing under this name on NPM is this project:

https://github.com/onefinestay/react-daterange-picker

I'm not sure which one you *really* love ;) Anyways, this project looks abandoned, so I contacted the owners if they wanted me to take over and maintain the project (and replace the old version with this one, compatible with newest versions of React). They refused, after a long time they "maintained" the library for a day or two and there's silence again :(

**Comment by Hybridx24** [comment]
Thank you for the quick response.

The issue with manually supplying the git URL as a dependency is that for some reason it _still_ installs the incorrect NPM version (I tried `npm install git+https://github.com/wojtekmaj/react-daterange-picker.git` but it installs a totally different package with the same name). It's a shame because your calendar is absolutely incredible.

**Comment by wojtekmaj** [comment]
Rather than using a command, define it as a "version" of react-daterange-picker in package.json. Then, `npm install`. That should do the trick, or at least it did for me so keeping my fingers crossed for ya!

Also, thanks for warm words. It really keeps me going knowing there are people who appreciate hundreds of hours I spend on open source projects!

**Comment by Hybridx24** [comment]
Any chance you can share an example `package.json` with me here? I can't seem to get it right (it keeps installing a version by someone named `onefinestay`...)

And course! I have so much respect for anyone who spends their free time sharing awesome open source projects. I actually consider your work on par with SweetAlert, which I think is both programmatically and visually perfect, as well as a necessary addition to the community.

**Comment by wojtekmaj** [comment]
@Hybridx24,
I updated README as stated in #2. Should work fine, at least it works for me :)
