### ISSUE TITLE
Problem with input fields size

### ISSUE THREAD

**Issue by Retanaar** [wojtekmaj/react-daterange-picker#10]
I have proble with width of input text field. I see that in style component insert width with width of arrow spinners. I add this style 
.react-date-picker__button__input__input::-webkit-outer-spin-button,
.react-date-picker__button__input__input::-webkit-inner-spin-button {
    -webkit-appearance: none;
    margin: 0;
}
but it not help me.

**Comment by wojtekmaj** [comment]
Hello,
as the component lands in the context of your application, all global styles that you may have applied on your own or using other libraries will affect the appearance of React-DateRange-Picker. What you should do in this case is write your own CSS which will cancel out the changes.
Perhaps try with `padding: 0` or `display: none` as well?

**Comment by Retanaar** [comment]
Thanks for your answer, but I not understand what do your mean. Look, I have text field 
<input class="react-date-picker__button__input__input react-date-picker__button__input__day react-date-picker__button__input__input--hasLeadingZero" name="day" max="30" min="1" placeholder="--" required="" type="number" value="1" style="width: 22.2188px;"> It text field show "1" but component calculate it width as  style="width: 22.2188px;" but it too big size. padding-right of this input field is zero and margin-right too. And what element must have display: none?

**Comment by wojtekmaj** [comment]
I meant `.react-date-picker__button__input__input::-webkit-outer-spin-button` you have mentioned.

**Comment by Retanaar** [comment]
Hello Wojtek,
I added this one style 
```
.react-date-picker__button__input__input::-webkit-outer-spin-button,
.react-date-picker__button__input__input::-webkit-inner-spin-button{
    -webkit-appearance: none;
    margin: 0;
    -moz-appearance: none;
    display: none;
}
```
And it didn't help me. Could your tell me where in component calcaulated width of input fields  I will try to debug it.

**Comment by wojtekmaj** [comment]
I'm on my mobile but I believe it's called updateInputWidth and it is in wojtekmaj/react-date-picker repo (React-DateRang-Picker uses two of these to create a range picker). It's actually very simple, it creates a span element, measures it and applies the width to the input element.
To see what goes wrong in your case I'd need a minimal reproduction repo. Otherwise I can just advise to turn it off by adding `width: auto !important` to input elements to turn it off.

**Comment by Retanaar** [comment]
Thank you, Wojtek, width: auto !important was really helpfull advise!

Another question, could I set some param that calendar open under the input fields only? Because now it try to find a free place for opening.

**Comment by wojtekmaj** [comment]
For that you need to have a custom CSS without this feature, or simply overwrite the styles of the class that puts the calendar above the input.

**Comment by Mohammed-Hameed** [comment]
Hello, Wojtek, I am trying to have a different date range in date-range-picker. I couldn't get proper documentation for it. Is there any way to have different from and to date date-range-picker

**Comment by wojtekmaj** [comment]
@Mohammed-Hameed 

You can use `~` in CSS selector to select inputGroup that comes after the divider, for example:

```css
.react-daterange-picker__range-divider ~ .react-daterange-picker__inputGroup input { 
  outline: 1px solid red;
}
```

This results with the following on our demo page:

![obraz](https://user-images.githubusercontent.com/5426427/64919634-7c864880-d7ad-11e9-8312-ad4f27731d70.png)
