### ISSUE TITLE
Month selection buttons not working 

### ISSUE THREAD

**Issue by jpaulomotta** [wojtekmaj/react-daterange-picker#100]
I'm using version 3.2.0, but the issue was also present on version 3.1.0

I recorded a video of the problem.

It seems that when the dialog box changed its size the month buttons stopped working and the dialog closes. If the user scrolls and the dialog opens to the bottom of the input, it works perfectly.

![Screen Recording 2021-07-30 at 18 02 25](https://user-images.githubusercontent.com/1813007/127712582-2395d439-4835-4100-967b-38d7384bfd77.gif)

**Comment by wojtekmaj** [comment]
Try v3.4.0. It contains a fix that should prevent this.
