### ISSUE TITLE
Could not find a declaration file for module '@wojtekmaj/react-daterange-picker'.

### ISSUE THREAD

**Issue by ClusterH** [wojtekmaj/react-daterange-picker#104]
@wojtekmaj/react-daterange-picker": "^3.3.0"
"@types/wojtekmaj__react-datetimerange-picker": "^3.0.2",
"react": "^17.0.1",
"typescript": "^4.1.5",

I use yarn, not npm.

when I import the package, I got error as above.
` import DateRangePicker from '@wojtekmaj/react-daterange-picker'`

![image](https://user-images.githubusercontent.com/58984914/132378934-5723e46d-f1c1-4daf-8959-1878ceabfa0e.png)

**Comment by wojtekmaj** [comment]
Please raise an issue in DefinitelyTyped repo instead. There's nothing we can do about the typings here.

**Comment by davidalvarezr** [comment]
`npm install @types/wojtekmaj__react-datetimerange-picker`
 
was difficult to find. source: https://stackoverflow.com/questions/66233124/typescript-error-using-react-daterange-picker-no-overload-matches-this-call
