### ISSUE TITLE
Calendar menu being cutoff

### ISSUE THREAD

**Issue by lanceschi** [wojtekmaj/react-daterange-picker#105]
Hello @wojtekmaj,

and thanks for the awesome component. I'd like to have some advice on how to deal with component positioning.

If I set ```<DateRangePicker />``` ```positiong: relative``` the calendar menu is going to be cut off. Please consider that I set ```overflow-x: auto``` in the parent ```div```. Here's a sample picture:
https://drive.google.com/file/d/1tuI8i0Cgrv3V0GU06tIOG4XYgJREHS1x/view

If instead I set ```<DateRangePicker />``` ```positiong: absolute``` the calendar menu is going to positioned correctly above all the other DOM elements but sadly the input won't move while scrolling with the mouse. Here's another sample picture:
https://drive.google.com/file/d/17xViszkonaHk21T4KU00aaw0CaXoG5bc/view

Any help appreciated. Thanks

**Comment by wojtekmaj** [comment]
I don't think there's an easy way to get around that. Your best options are:

- Remove overflow: hidden when calendar is opened
- Build a mechanism that moves fixed DateRangePicker as you scroll the page

**Comment by lanceschi** [comment]
Hello @wojtekmaj,

and thanks for the reply, I successfully used [React Portal][portal-url] in the past in order to easily overcome these HTML element position shortcomings.

Please consider this solid React feature as a possible candidate solution in the future.


[portal-url]: https://reactjs.org/docs/portals.html#gatsby-focus-wrapper

**Comment by wojtekmaj** [comment]
Just a heads up: in ce9385cbec5a344045cb630c50330af43795575b, support for `portalContainer` prop was added, which makes it possible to render Calendar using a Portal.

**Comment by dvolp91** [comment]
Hello @wojtekmaj could you please make a tagged realeased for this feature? thanks in advance.

**Comment by blkdr** [comment]
Hello @wojtekmaj 

Im trying to use the `portalContainer` prop as listed on the available props for v3.4.0 but is not working, after further inspection it appears that is listed but it did not went live on the npmjs package.

Can you help? Greetings
