### ISSUE TITLE
Can the date range fall back to `minDate` and `maxDate` when cleared?

### ISSUE THREAD

**Issue by Kayx23** [wojtekmaj/react-daterange-picker#109]
I have `minDate` and `maxDate` props set and would like the picker to fall back to the available range when users clear their range by clicking on "`X`". Is this possible? 

Currently the picker clears the range and resets to `--/--/----      --/--/----`

Thanks!

**Comment by wojtekmaj** [comment]
You could use React-DateRange-Picker in a controlled way (`value` + `onChange`), and set value to `minDate` when `onChange` gets `null`.
