### ISSUE TITLE
How to force the calendar to open downwards? 

### ISSUE THREAD

**Issue by Kayx23** [wojtekmaj/react-daterange-picker#110]
Is there an easy way to force the calendar to open downwards other than styling the React Calendar somehow myself? 

The calendar is opening upwards (overlapping with the navbar but this should be relatively easy to fix by setting z-index) and I prefer it to open downwards every time, regardless of the available space at the top. How do I do this? 

![unnamed](https://user-images.githubusercontent.com/39619599/145243644-48f5e46e-1cb8-4cd6-a61e-0daaa9d647d5.jpg)

**Comment by Kayx23** [comment]
Sometimes it opens upwards, sometimes downwards (when there is not enough space at the top based on the viewport), and sometimes in the middle covering the datetime picker (with sufficient spaces both at the top and bottom)...

**Comment by wojtekmaj** [comment]
Other than some CSS styling with lots of `!important`, I don't see a way to do this.
