### ISSUE TITLE
Date not selectable on Safari when RadioGroup is used.

### ISSUE THREAD

**Issue by hariombalhara** [wojtekmaj/react-daterange-picker#114]
See the functionality on Safari, you won't be able to select a date range - https://codesandbox.io/s/react-daterange-picker-bug-with-radiogroup-from-radix-ui-on-safari-v9pji

The issue occurs because on Safari there `focusin` event fires on the radio-group element(because it is focussable). That event is outside the DOM of daterange-picker which causes the click that was supposed to select the date to actually close the picker.

**Comment by PaulAtST** [comment]
I am currently having the same issue, is there a fix for this?

**Comment by wojtekmaj** [comment]
The original CodeSandbox works fine for me on Safari 16.0 (17614.1.25.9.10, 17614).

**Comment by PaulAtST** [comment]
@wojtekmaj Humm thats interesting so so far I have tested the sandbox and my code on the following safari browsers: 
A Mac with safari 15.6.1
An iPad with iPad os 15.7
An iPhone with iOS 16.0 

And all three are showing the same issue that when I select the first date in the date picker the date picker closes and onChange is not getting called. 

I dug a little deeper and was able to solve the issue by manually setting a tab index on the element `<div class="react-calendar">`. It might be worth adding a tab index property to the DateRangePicker component so users can customize the tab index
