### ISSUE TITLE
Code is not sync with the newest version in spite of package.json version

### ISSUE THREAD

**Issue by henarivanaa** [wojtekmaj/react-daterange-picker#118]
![Screenshot from 2022-04-18 15-26-43](https://user-images.githubusercontent.com/58682046/163780635-3011a4cf-cfac-4c4f-8403-6e561e802350.png)
![Screenshot from 2022-04-18 15-26-59](https://user-images.githubusercontent.com/58682046/163780645-562f0e9a-c34f-4b48-bf26-ea47174c4278.png)

i have done yarn cache clean and deleting then reinstalling the package, this ss is taken from node modules, the issue is theres no createPortal imported or portalContainer props when the version says its the latest. Help will be appreciated, thanks!

**Comment by wojtekmaj** [comment]
Features in question were not released. They were not mentioned in any release notes yet, and npm README does not include portalContainer prop.
