### ISSUE TITLE
How to rename weekdays from 'Mon','Tue','Wed'.... to 'M','T','W',...

### ISSUE THREAD

**Issue by AmritPhalake** [wojtekmaj/react-daterange-picker#119]
Hi @wojtekmaj ..... How to rename weekdays from 'Mon','Tue','Wed'.... to 'M','T','W',...

**Comment by blkdr** [comment]
Hello!

You can use the `formatShortWeekday` prop from the [react-calendar component](https://github.com/wojtekmaj/react-calendar#props).

The [Readme](https://github.com/wojtekmaj/react-daterange-picker#calendar) says that

> DateRangePicker component passes all props to React-Calendar [...]
