### ISSUE TITLE
Access to onOpen & onClose Events

### ISSUE THREAD

**Issue by Joeao** [wojtekmaj/react-daterange-picker#12]
Hey guy,

Thanks for the awesome projects, been using this and calendar on my app.

A little feedback: Currently clicking on leading zeroes won't cause the calendar to appear. This is also the case with clicking the slashes between dates. I won't make assumptions as to whether this is intended behaviour, but it's something I'd like to change in my implementation.

I've tried manually forcing the calendar open when a click occurs on the input group wrapper by setting an open state on the parent onClick, but I can't tell the parent when the picker has closed, so it only works one time.

Having access to onOpen and onClose events regardless of a value change would help us have greater control over the picker. Therefore I request this as a feature.

Thanks a lot, let me know if I'm overlooking something. Or if this is something you're happy with including in the project I can make a pull request.

Joe

**Comment by wojtekmaj** [comment]
Related to wojtekmaj/react-calendar#146

**Comment by wojtekmaj** [comment]
Added in de1f7b7f8a7fd5fbe4ea91a337707b43c35d87db and released in v2.2.0.
