### ISSUE TITLE
(0 , _utils.callIfDefined) is not a function

### ISSUE THREAD

**Issue by moses-bowman** [wojtekmaj/react-daterange-picker#121]
react-datetime-picker just stopped working. clicking the component throws an error which states `(0 , _utils.callIfDefined) is not a function`.

![image](https://user-images.githubusercontent.com/40249465/187825653-a9a7b9f5-7553-4a9b-9c68-90e023ddcc4b.png)

`package.json`
```json
// ...
"devDependencies": {
    // ...
    "babel-cli": "^6.24.0",
    "babel-core": "^6.26.3",
    "babel-preset-react": "^6.23.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "webpack": "^3.12.0"
  },
"dependencies": {
    // ...
    "react-date-picker": "^8.4.0",
    "@wojtekmaj/react-daterange-picker": "^2.5.0"
  }

```

**Comment by wojtekmaj** [comment]
You're using super old React-DateRange-Picker version. Update and the problem will be gone.
