### ISSUE TITLE
CSS classes on initial state

### ISSUE THREAD

**Issue by leppi** [wojtekmaj/react-daterange-picker#13]
On the month view "button.react-calendar__tile" has class "react-calendar__tile--rangeStart" / "react-calendar__tile--rangeEnd" only when range is selected by user. On initial state start and end points has only the class "react-calendar__tile--active"

I've highlighted the start and end dates on my calendar and when I set user's previous selections on componentDidMount the above classes are missing and my calendar looks silly :)

**Comment by wojtekmaj** [comment]
For support on calendar, please see [React-Calendar](/wojtekmaj/react-calendar), which React-DateRange-Picer uses internally :)

Looks like this has already been reported in wojtekmaj/react-calendar#153 and fixed, but not yet published. Will publish soon, thanks!
