### ISSUE TITLE
Calendar appears on top, should be on bottom, gets cut off by screen.

### ISSUE THREAD

**Issue by nikolai-tenev** [wojtekmaj/react-daterange-picker#14]
Not sure why but the calendar appears on the wrong position. Here's a [screenshot](https://pasteboard.co/HMdjGXa.png).

**Comment by wojtekmaj** [comment]
Possibly related to wojtekmaj/react-date-picker#110.

I'm gonna need a minimal reproduction for this issue (you could pack a repo and attach it here in the comments). This has likely something to do with styling / element position I did not think of.

**Comment by wojtekmaj** [comment]
Actually, one idea. As React-DateRange-Picker detects collisions between the element and document.body, could it be that document.body ends just below the picker? Try applying `body { min-height: 100vh }` css to your website.

**Comment by Zertz** [comment]
@wojtekmaj I'm displaying the picker in a modal with hidden overflow so there is no collision per se, but the picker gets cut off.

Is there a way I could tell the picker to pop on top of the input instead of below?

![image](https://user-images.githubusercontent.com/2636763/69757874-14000400-112c-11ea-8fda-3371e29b14ef.png)

**Comment by wojtekmaj** [comment]
Try adding overflow: auto to a container inside the popup. React-DateRange-Picker should detect this and place calendar better.

**Comment by Zertz** [comment]
Does not seem to work, we ended up hacking together a solution with `position: fixed;` so it can overflow out of the modal without having a scroll.

**Comment by WholemealDrop** [comment]
Running into this as well. React-DateRange-Picker positioned at the bottom of a material-ui card, locally opens upwards when opened, in prod environment it opens downwards and gets hidden. Adding `overflow: auto` to the containing card allows it to be shown. Would still prefer it to be opening upwards but it seems to work.
