### ISSUE TITLE
React TypeScript No style ?

### ISSUE THREAD

**Issue by BenJ4u** [wojtekmaj/react-daterange-picker#147]
Hello, I am looking to remove the default style or simply modify the active buttons on the calendar.
When I try to import **DateRangePicker** module from **'@wojtekmaj/react-daterange-picker/dist/entry.nostyle'** an error occurs:

> Could not find a declaration file for module '@wojtekmaj/react-daterange-picker/dist/entry.nostyle'.

What to do ?

**Comment by wojtekmaj** [comment]
Types are externally provided via DefiintelyTyped. You can raise an issue or contribute in this repo :)

**Comment by ArthurMiroslavsky** [comment]
Same issue(

**Comment by BenJ4u** [comment]
> Types are externally provided via DefiintelyTyped. You can raise an issue or contribute in this repo :)

Thank you for your reply. Not being very familiar with Typescript and React typing (this is my first React project here), I understand the DefintelyTyped logic but I can't seem to apply it. However, I understood that there was a typing defined for the basic package, but anyway it turns out to be impossible for me to modify the design of the date range picker as I wish. Although I greatly appreciate the work you have provided.

**Comment by wojtekmaj** [comment]
Thanks for the kind words!

The thing is DefinitelyTyped provides types for this package, I have nothing to do with it. So to get that issue resolved, an issue must be filed against the DefinitelyTyped repository. Seems like an easy fix, since the types for both imports should be identical.

**Comment by BenJ4u** [comment]
> Thanks for the kind words!
> 
> The thing is DefinitelyTyped provides types for this package, I have nothing to do with it. So to get that issue resolved, an issue must be filed against the DefinitelyTyped repository. Seems like an easy fix, since the types for both imports should be identical.

Alright, I just figured it out! I will take the steps with DefinitelyTyped .

**Comment by ArthurMiroslavsky** [comment]
Thanks!
