### ISSUE TITLE
Version 4.0.0 produces warnings with server side rendering

### ISSUE THREAD

**Issue by finkrer** [wojtekmaj/react-daterange-picker#152]
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at Input (/node_modules/react-date-picker/dist/DateInput/Input.js:118:24)
    at YearInput (/node_modules/react-date-picker/dist/DateInput/YearInput.js:31:22)
    at div
    at DateInput (/node_modules/react-date-picker/dist/DateInput.js:232:5)
    at div
    at div
    at DateRangePicker (/node_modules/@wojtekmaj/react-daterange-picker/dist/DateRangePicker.js:93:5)
```

**Comment by wojtekmaj** [comment]
That's new for me, but I'm not surprised too much. It was introduced in 4de8245bf184c111c29f6079082817804ae5ce5c and the reason for this effect is to apply CSS `width` to an input based on its content width. If we use `useEffect` here, the UI jumps for a split second because the measurements are done too late.

**Comment by wojtekmaj** [comment]
Sorry, which parts of the docs, or which post, are you referring to?

**Comment by finkrer** [comment]
Sorry, I should've highlighted that. The error message links to this page: https://reactjs.org/link/uselayouteffect-ssr

**Comment by wojtekmaj** [comment]
Thanks!

Neither of these options are appealing to me.

* Converting to `useEffect` is out of question for the reasons described above
* "Lazy loading" component effectively breaks SSR rendering of the component which, aside from the measurements that must be done in the browser, is perfectly fine to render server side.

The only solution that makes any sense to me is [this one](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85?permalink_comment_id=2911761#gistcomment-2911761) - I'll go with this.

**Comment by rscotten** [comment]
> you'll have to update it yourself e.g. using `yarn up react-date-picker -R`, reinstall React-DateRange-Picker

@wojtekmaj  Perhaps you mean `yarn upgrade react-date-picker -R` ?

**Comment by wojtekmaj** [comment]
> > you'll have to update it yourself e.g. using `yarn up react-date-picker -R`, reinstall React-DateRange-Picker
> 
> @wojtekmaj  Perhaps you mean `yarn upgrade react-date-picker -R` ?
> 
> 

For legacy versions of Yarn, as far as I can remember, the command you proposed would be correct. :)
