### ISSUE TITLE
In most range pickers you have the ability to have 2 calendars (adjacent months)

### ISSUE THREAD

**Issue by tahergalal** [wojtekmaj/react-daterange-picker#17]
Is it possible to have 2 adjacent calendars to allow for selecting ranges accross 2 months and if so how?

**Comment by wojtekmaj** [comment]
Hi,
this is planned and is tracked in wojtekmaj/react-calendar#82. Sorry, but I can't give any dates at the moment.

**Comment by Kanuny** [comment]
Is there any updates? I really want this feature in my project as soon as possible so if you need any help I can assist you if some work already in progress or develop this feature by myself with PR if not.

**Comment by wojtekmaj** [comment]
React-Calendar 3.0.0-beta is out, I only need help with the testing. See https://github.com/wojtekmaj/react-calendar/issues/216 for details!

I didn't test that but I'm fairly certain that you can even use Yarn's `resolutions` to force React-Date-Picker to use React-Calendar 3.0.0-beta right now, and passing `showDoubleView ` to DatePicker will cause the calendar to pick it up.

**Comment by Kanuny** [comment]
Great to know. Thanks a lot for implementing this feature.

**Comment by wojtekmaj** [comment]
Recent versions are using React-Calendar 3.0, so I'm closing this issue.
