### ISSUE TITLE
Calendar Pop Up Collision on Fixed

### ISSUE THREAD

**Issue by jesseagleboy** [wojtekmaj/react-daterange-picker#193]
I am trying to understand if there is some automatic handling of the pop-up calendar for the date-range picker. I have the picker on a component set to a "sticky" position for the picker's absolute positioning. If I do not scroll through the page at all and open up the calendar, the calendar will open below the picker. If I scroll any amount on the page, the calendar will open up above the picker which usually creates a collision with a header in close proximity, hiding under the header. I could fix the header to be layered under the calendar but there is a lot of negative space below the calendar that the calendar can fill.
1. Is there some weird CSS bug that scrolling adjusts the inset's "auto" value of the calendar's positioning?
3. Does the daterange-picker have some type of "Popper" property under the hood which can be used or is this something to apply on my own?

Due to work-related property, the screenshots may be vague but do show the calendar opening up on different sides:

<h4>Calendar down</h4>
<img width="390" alt="calendar-down" src="https://user-images.githubusercontent.com/6441776/208993448-df07f691-2ebe-4502-8e43-2e062094a3dc.png">

<h4>Calendar up</h4>
<img width="377" alt="calendar-up" src="https://user-images.githubusercontent.com/6441776/208993622-b9b90c3b-36c3-4d1d-984e-6e08f8c5cd26.png">

**Comment by wojtekmaj** [comment]
Hi,
yes, there's automatic collision handling implemented in this project, and it used react-fit under the hood.
Position: fixed is a problematic container, as its collision needs to be recalculated on scroll.
If you have any suggestions on improving the algorithm, feel free to contribute to react-fit!
