### ISSUE TITLE
NPM/Yarn install command incorrect

### ISSUE THREAD

**Issue by jrubins** [wojtekmaj/react-daterange-picker#2]
Hey, just an FYI that it looks like your NPM/Yarn install command is incorrect. The command you list:
```
yarn add react-daterange-picker
```
actually installs this package: https://github.com/onefinestay/react-daterange-picker (which is the one on the NPM registry: https://www.npmjs.com/package/react-daterange-picker).

I think you may need to register the package on NPM as a different name (perhaps scoped to your username?) or if it's already under a different name, it might be nice to update your README (I'm glad to submit a PR if you let me know the actual location!).

Just noticed this when trying to help someone out on [StackOverflow who's trying to install your package](https://stackoverflow.com/questions/49418417/npm-install-github-url-downloading-from-npm-instead-of-github/49418549#49418549).

Oh, also, it seems like the demo link is broken at the moment: http://projects.wojtekmaj.pl/react-daterange-picker/ returns a 404.

**Comment by wojtekmaj** [comment]
Hi,
thanks for pointing that out. I was preparing to release it on NPM and all README was crafted for this situation in mind. It looks like it's not going to happen anytime soon, so I changed the commands. Hope it will work fine for you now! Let me know, if not, I'll reopen.
