### ISSUE TITLE
How to change the style when choosing a period of time

### ISSUE THREAD

**Issue by MeiJunNa** [wojtekmaj/react-daterange-picker#20]
![image](https://user-images.githubusercontent.com/30679487/53864361-3c3c5580-4027-11e9-8022-bf42df5f7bcd.png)

**Comment by wojtekmaj** [comment]
React-DateRange-Picker uses React-Calendar under the hood. Here are the [default Calendar styles](https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.less) that you can overwrite if you need it.

**Comment by MeiJunNa** [comment]
> React-DateRange-Picker uses React-Calendar under the hood. Here are the [default Calendar styles](https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.less) that you can overwrite if you need it.

Thank you for your answer
