### ISSUE TITLE
"Start date - End date" placeholder?

### ISSUE THREAD

**Issue by avivash** [wojtekmaj/react-daterange-picker#21]
Hi, I'm wondering if it's possible for us to pass in our own text inputs to be used with this plugin? Taking a quick look through the source code, I didn't come across anything to do this, but I may be wrong?

I'm basically looking to use my own inputs, so I can show `placeholders` when no date is selected; something similar to `Start Date - End Date`. I can probably achieve this through adding my own styles and setting some flags in the `onChange` prop, but I'm wondering if there's a more straight forward out-of-the-box solution?

Thanks!

**Comment by wojtekmaj** [comment]
Hi,
no, you can't pass your own inputs into React-DateRange-Picker. You can definitely add your own styles. Modifying placeholders may be tricky though; I didn't come up with a solution that would work well for a picker this flexible and supporting this many languages.

**Comment by miguelski** [comment]
looking for the same kind of placeholders Start Date - End Date
