### ISSUE TITLE
Is there a posibility to define how values are formatted in the inputs

### ISSUE THREAD

**Issue by tahergalal** [wojtekmaj/react-daterange-picker#23]
I know you can format the inputs of the calendar but i would like to perform that also for the inputs so for example have a date in the format dd/MMM/yyyy

**Comment by wojtekmaj** [comment]
Hi,
you modify the format by using `locale` prop. React-DateRange-Pickder automatically picks format that fits given locale best.

**Comment by tahergalal** [comment]
this does not solve the issue a date format is different from a locale a locale can be en,de but I may have a requirement to support a certain format

**Comment by wojtekmaj** [comment]
Understood! React-DateRange-Picker is powered by React-Date-Picker. I'm tracking this feature in recently revisited wojtekmaj/react-date-picker#40 :) Stay tuned!

**Comment by wojtekmaj** [comment]
Thanks @tahergalal for your suggestion. Next release of React-DateRange-Picker will have what you asked for! :)

**Comment by wojtekmaj** [comment]
@tahergalal Version 2.2.0 is out and it includes the feature you requested :)
