### ISSUE TITLE
Unselect / Clear date range

### ISSUE THREAD

**Issue by hlarcher** [wojtekmaj/react-daterange-picker#24]
Is there a way to unselect / clear the date range natively in the component?

I've also tried to set the value back to null but the browser becomes unresponsive and yields no error.

**Comment by wojtekmaj** [comment]
`null` value should be okay... Or `[null, null]` if that doesn't work, but that's odd if the first one doesn't work and should be considered a bug.

**Comment by rudmanmrrod** [comment]
I use your example sandbox and modify, and get:

`TypeError
yearMonth is undefined`

Here de example: https://codesandbox.io/s/keen-mcnulty-60dt0 or de code is:

```
import React from "react";
import DateRangePicker from "react-daterange-picker";
import "react-daterange-picker/dist/css/react-calendar.css";
import originalMoment from "moment";
import { extendMoment } from "moment-range";
const moment = extendMoment(originalMoment);

class Example extends React.Component {
  constructor(props, context) {
    super(props, context);

    const today = moment();

    this.state = {
      isOpen: false,
      value: moment.range(today.clone().subtract(7, "days"), today.clone())
    };
  }

  onSelect = (value, states) => {
    this.setState({ value, states });
  };

  onToggle = () => {
    this.setState({ isOpen: !this.state.isOpen });
  };

  clear = () => {
    this.setState({ value: [null, null] });
  };

  renderSelectionValue = () => {
    return (
      <div>
        <div>Selection</div>
      </div>
    );
  };

  render() {
    return (
      <div>
        <div>{this.renderSelectionValue()}</div>

        <div>
          <input
            type="button"
            value="Toggle date picker"
            onClick={this.onToggle}
          />
          <button onClick={this.clear}>Clear</button>
        </div>

        {this.state.isOpen && (
          <DateRangePicker
            value={this.state.value}
            onSelect={this.onSelect}
            singleDateRange={true}
          />
        )}
      </div>
    );
  }
}

export default Example;
```

**Comment by wojtekmaj** [comment]
@rudmanmrrod You're not running this package. This package is under name `@wojtekmaj/react-daterange-picker` on NPM.

**Comment by oahmadseecs** [comment]
Hey @hlarcher ? Did you solve this, I am facing the same problem now...

**Comment by wojtekmaj** [comment]
Is setting value to null not working for you?

**Comment by mefik1337** [comment]
> Is setting value to null not working for you?

@wojtekmaj it's not working. Im trying something like that: dateRange = dateRange === '' ? [null, null] : dateRange inside od calendar component but im getting error: Warning: Failed prop type: 'value' must be a moment or a moment range

but if do normally in my onReset func. dateRange = null then it crash my app. 

Any solutions for this?
