### ISSUE TITLE
 ReferenceError: Unknown plugin "@babel/proposal-class-properties"

### ISSUE THREAD

**Issue by ipnuds** [wojtekmaj/react-daterange-picker#27]
Hi i'm importing nostyle mode but get error

in ./node_modules/react-fit/dist/Fit.js
Module build failed: ReferenceError: Unknown plugin "@babel/proposal-class-properties"

and if using styled one get unexpecetd token .  (dot)

could you show me how to fix?

**Comment by wojtekmaj** [comment]
What bundling system are you using? You shouldn't be using shipped .babelrc in React-Fit 🤔

**Comment by ipnuds** [comment]
I'm using this ssr boilerplate https://github.com/Brigad/ssr-starter-pack the old version.
use webpack 3, node 8 and semantic-ui-react.

**Comment by wojtekmaj** [comment]
I'm afraid that this starter pack uses Babel a little too eagerly. 

Workaround for this issue would be to simply install missing plugins.

For the `unexpected token .` the solution would be to add style-loader & css-loader for `.css` files in your Webpack config.
