### ISSUE TITLE
Failed Prop-type of type 'Array', expected 'List'

### ISSUE THREAD

**Issue by jportella93** [wojtekmaj/react-daterange-picker#28]
In `DateRangePicker.jsx` the prop `dateStates` is an array, however in `CalendarDate.jsx` it expects an instance of `Immutable.List`, this is raising a failed prop types error.

**Comment by wojtekmaj** [comment]
Are you sure this is the right repo? I don't have dateStates and I don't require Immutable.List :)

**Comment by jportella93** [comment]
LOL, sorry I was using https://github.com/onefinestay/react-daterange-picker 😅
