### ISSUE TITLE
keep the calendar open after selection

### ISSUE THREAD

**Issue by morscad** [wojtekmaj/react-daterange-picker#29]
Can I keep the calendar open, even after I selected the date range, but hide the wrapper footer element? 
basically I only need the wrapper to be visible on screen and I need it to be persistent even after I finish my selection

**Comment by wojtekmaj** [comment]
Hi,
no, sadly that's not possible. A quite hacky workaround would be to set isOpen flag to false and then immediately to true, which would cause it to re-open.

**Comment by ashmoop** [comment]
Can confirm. Adding an isOpen state with a special function called onCalendarClose will keep the calendar open, but it does flicker a bit. Would be nice to have a props we could pass to keep it static.
