### ISSUE TITLE
The Demo link appears to be broken

### ISSUE THREAD

**Issue by jensstalder** [wojtekmaj/react-daterange-picker#3]
http://projects.wojtekmaj.pl/react-daterange-picker/

mentioned in the readme does not exist (404)

**Comment by wojtekmaj** [comment]
Hey, thanks for the heads up. I'm on it. Mind you, this package has not been officially released yet as we're disputing over npm package name.

**Comment by wojtekmaj** [comment]
Thanks again. The demo page is up! :)
