### ISSUE TITLE
Add style prop

### ISSUE THREAD

**Issue by pavinduLakshan** [wojtekmaj/react-daterange-picker#30]
It would be nice to add `styles` prop so that it is much easy to customize styles.

**Comment by wojtekmaj** [comment]
Hi, this won't be worked on. React-DateRange-Picker is quite complex, and providing good support of `style` to all elements that require it would be too much to ask. I suggest using `entry.nostyle` and adding your own stylesheet if you need fancy styles.

**Comment by JonnyPillar** [comment]
Hey @wojtekmaj, thanks for the work you have put in on this. 

I agree with @pavinduLakshan that it would be great to add in a styles or docs on how to override the default styles on elements such as the input groups (Not so much the calendar popup itself).

Just being able to set an extra className isn't idea as then I have to work to override everything in CSS which is pretty hacky.

It maybe this is already possible and that I have missed it but it would be a useful extension of the package
