### ISSUE TITLE
Error: Can't resolve 'react-date-picker/dist/DateInput'

### ISSUE THREAD

**Issue by Daleksander** [wojtekmaj/react-daterange-picker#302]
Compiled with problems:
×
ERROR in ./node_modules/@wojtekmaj/react-daterange-picker/dist/DateRangePicker.js 14:40-83
Module not found: Error: Can't resolve 'react-date-picker/dist/DateInput' in '/home/Myproject/node_modules/@wojtekmaj/react-daterange-picker/dist'

My react version 16.8,
"@wojtekmaj/react-daterange-picker": "^4.2.1",

In node modules i got all dist files, but on npm start it fails. Do you have any idea what can I do to fix it ?

**Comment by wojtekmaj** [comment]
By updating to the latest version, 4.x is no longer supported.
