### ISSUE TITLE
Disabling certain dates

### ISSUE THREAD

**Issue by emyrue** [wojtekmaj/react-daterange-picker#304]
Is there a way to make it so you can't pick certain date ranges, or at least style certain date ranges on the calendar so it's clear that they've already been picked?

**Comment by wojtekmaj** [comment]
You can't disable certain dates in the input (how would we even approach this? Ughhh! But you totally can in the calendar, using `tileDisabled` prop. See https://github.com/wojtekmaj/react-calendar README for details.

**Comment by dlsso** [comment]
This only prevents you from clicking on the date, it still allows ranges that contain disabled dates.

The expected/desired behavior would be to disable all days that would include any unavailable days ([like this](https://react-spectrum.adobe.com/react-aria/DateRangePicker.html#unavailable-dates)) or at least throw an error.
