### ISSUE TITLE
DatePicker container

### ISSUE THREAD

**Issue by OrhayBenaim** [wojtekmaj/react-daterange-picker#309]
Hi, is there a way or plans on adding a way to append custom components such as last month button to the date picker calendar?

**Comment by wojtekmaj** [comment]
Not my top priority, but it's already requested in the React-Calendar repo, so I may look into it when I get some free time.

**Comment by davidgoli** [comment]
Would be great to get an update on this!

**Comment by davidgoli** [comment]
in particular, I think this would need to come from this library, which provides the actual "position: absolute" container component. React-Calendar doesn't use absolute positioning, so it's easy to just add such buttons directly next to the react-calendar component as explained here: https://github.com/wojtekmaj/react-calendar/issues/226. However, that's not possible with react-daterange-picker.
