### ISSUE TITLE
Error with next.js

### ISSUE THREAD

**Issue by kingRayhan** [wojtekmaj/react-daterange-picker#31]
I just installed and copied the example code from readme.md
![image](https://user-images.githubusercontent.com/7611746/58905636-05f89a00-872c-11e9-974e-161329a5e028.png)

And then get this error,
![image](https://user-images.githubusercontent.com/7611746/58905518-c467ef00-872b-11e9-933f-df857e9d9a5c.png)

My project is on **Next.js**

**Comment by wojtekmaj** [comment]
You can [import React-DateRange-Picker without the styles](https://github.com/wojtekmaj/react-daterange-picker#custom-styling) and add CSS styles on your own, if your environment doesn't support CSS modules.
