### ISSUE TITLE
Build Error Occured : With the latest Release of yours

### ISSUE THREAD

**Issue by JohnsonJero03** [wojtekmaj/react-daterange-picker#311]
**HTML Reference Error Occured :** 

For about 2 months, we have used your Daterange-picker, Today we have tried to move our code to production.

**ReferenceError: HTMLElement is not defined
    at file:///opt/atlassian/pipelines/agent/build/node_modules/@wojtekmaj/react-daterange-picker/dist/esm/DateRangePicker.js:249:43
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24) {
  type: 'ReferenceError'**

**React Version: 17.0.2**

It matches compatiable version that you've provided in you document:
![Screenshot from 2023-07-28 09-58-41](https://github.com/wojtekmaj/react-daterange-picker/assets/52404852/36f6abe4-484d-4ab0-b02b-05fe52662239)

**React version | Newest compatible React-DateRange-Picker version
-- | --React version | Newest compatible React-DateRange-Picker version
-- | --
≥16.3 | latest
≥16.0 | 2.x
≥16.3 | latest
≥16.0 | 2.x**

**Comment by JohnsonJero03** [comment]
@JohnsonJero03  Issue: Build Error Occured: With the latest Release of yours #311


![Screenshot from 2023-07-28 10-13-01](https://github.com/wojtekmaj/react-daterange-picker/assets/52404852/35277293-8870-4967-bb3f-3018cacf6d79)

**Comment by wojtekmaj** [comment]
Thanks for the heads up - looking into it now
