### ISSUE TITLE
Error on render

### ISSUE THREAD

**Issue by alex-clear** [wojtekmaj/react-daterange-picker#312]
Hi
**You created great project, thanks**
I just started to use it and got next error
![Screenshot 2023-07-30 at 12 05 43](https://github.com/wojtekmaj/react-daterange-picker/assets/97834715/d96a42f8-2cbb-4f62-8325-2dd53f663784)
I use exact configuration by provided example in repo
Will appreciate for your help
Thanks

**Comment by wojtekmaj** [comment]
What's your setup?

**Comment by vishal-gloify** [comment]
Hi @wojtekmaj,

I am getting the same error

<img width="857" alt="Screenshot 2023-07-31 at 12 26 35 PM" src="https://github.com/wojtekmaj/react-daterange-picker/assets/81747167/142b6176-1035-4b7b-888e-7c61b4ac7e38">
<img width="1435" alt="Screenshot 2023-07-31 at 12 29 32 PM" src="https://github.com/wojtekmaj/react-daterange-picker/assets/81747167/db75710e-810c-47a0-b899-d77ef4963aa9">

**Comment by wojtekmaj** [comment]
This doesn't help me at all if there's no additional info.

**Comment by wojtekmaj** [comment]
Fixed in v5.4.2.

**Comment by vishal-gloify** [comment]
Thanks @wojtekmaj
