### ISSUE TITLE
How can I get rid of this warning?

### ISSUE THREAD

**Issue by sangdth** [wojtekmaj/react-daterange-picker#313]
This warning on `portalContainer` on my nextjs project.

```
Warning: Failed prop type: DateRangePicker: prop type `portalContainer` is invalid; it must be a
function, usually from the `prop-types` package, but received `undefined`.This often happens 
because of typos such as `PropTypes.function` instead of `PropTypes.func`.
```

**Comment by wojtekmaj** [comment]
Seems to be caused by b9040d409e1b75644adf8da7f7aeacbc721a0859 which fixed #311. Perhaps we could replace ternary with object assignment 🤔

**Comment by sangdth** [comment]
Thank you, looking forward to the release. <3

**Comment by wojtekmaj** [comment]
Released!

**Comment by sangdth** [comment]
Thanks, I can confirm it's gone in my repo.
