### ISSUE TITLE
Type error when upgrading from version 5.0.1 to 5.1+ 

### ISSUE THREAD

**Issue by khyechun** [wojtekmaj/react-daterange-picker#315]
Version 5.1.0
![image](https://github.com/wojtekmaj/react-daterange-picker/assets/47170358/bb6fba94-5fbb-4781-a320-66e44e77a382)
Version 5.4.2
![image](https://github.com/wojtekmaj/react-daterange-picker/assets/47170358/4fcbc121-05eb-4646-9a6d-184230fc4d8d)

I'm getting an error after upgrading react-daterange-picker from version 5.0.1 to versions 5.1 and after.
Not sure if there's some dependency I need to update?

**Comment by wojtekmaj** [comment]
You might be running an ancient TypeScript version.
