### ISSUE TITLE
How to change week days name or month name 

### ISSUE THREAD

**Issue by nayanapp** [wojtekmaj/react-daterange-picker#330]
`<DateRangePicker
                minDate={new Date()}
                onChange={onRangeDateChange}
                value={[startDate, endDate]}
                locale="he"
                format="yyyy/M/d"
                clearIcon={false}
                calendarIcon={false}
                showDoubleView={true}
            />`
            
Above code will generate datepicker like below screenshot.
![image](https://github.com/wojtekmaj/react-daterange-picker/assets/158023202/88d6126c-f19c-418f-af3c-4bc99344f8a2)

I want to change week days name like ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת'] rather then יום א׳,יום ב׳ and so on..
How can I achieve this ?

**Comment by EdijsApse** [comment]
I achieved this using formatShortWeekday & formatMonthYear props.

**Comment by wojtekmaj** [comment]
This is the way :) Thanks for reading documentation.
