### ISSUE TITLE
Support react-calendar@5

### ISSUE THREAD

**Issue by aqeelat** [wojtekmaj/react-daterange-picker#340]
React calendar v5 is out
https://github.com/wojtekmaj/react-calendar/releases/tag/v5.0.0

**Comment by wojtekmaj** [comment]
I know, it's my own package 🤣

**Comment by wojtekmaj** [comment]
Closed in v6.0.0.

**Comment by aqeelat** [comment]
Ops 🤣 
[r/dontyouknowwhoiam](https://www.reddit.com/r/dontyouknowwhoiam/)

**Comment by wojtekmaj** [comment]
Haha, good one! Thanks for raising this though. Glad to hear it's being actively used :)
