### ISSUE TITLE
daterange-picker accepts invalid inputs

### ISSUE THREAD

**Issue by vishalrajole** [wojtekmaj/react-daterange-picker#42]
Using daterange picker in my react js application. 
Using version: 2.4.0

Issues:
- Input fields for date & month accepts any length values
- Input field for year field have min:1000  and max: 275760

![Screenshot 2019-08-20 at 11 53 13 AM](https://user-images.githubusercontent.com/4668780/63322462-1e4a7f00-c341-11e9-8f59-a3694560690a.png)

**Comment by vishalrajole** [comment]
@wojtekmaj @pmurphy-cs @victor-cordova

**Comment by banisirohi** [comment]
Having same issue. Is there a way to prevent user from entering input value.

**Comment by banisirohi** [comment]
@vishalrajole  this is a quick css fix to prevent user from entering rather selecting from calender icon.

.react-daterange-picker__inputGroup__input {
    pointer-events: none;
}

**Comment by Lander37** [comment]
Having the same issue as well, any way to check for invalid user inputs?

**Comment by hholzmann16** [comment]
I used this for checking formatting for input type "mm/dd/yyyy"

`    const inputs = document.querySelectorAll(
      ".react-daterange-picker__inputGroup__input"
    );
    // Check to make sure HTML tag is found
    if (inputs) {
      inputs.forEach(input => {
        // Ensure leading zero is shown once if needed
        if (input.name === "month" || input.name === "day") {
          input.addEventListener("keypress", e => {
            // Regex looks for typed leading "0", and removes because component already adds this
            e.target.value = e.target.value.replace(/^0+/, "");
          });
        }
      });
    }`

**Comment by hholzmann16** [comment]
@wojtekmaj This may help with the issue people are having for month and day being the wrong format, as well as the issue of being able to type in "001" for month (bug in your demo as well) for those who add the leading zero.
