### ISSUE TITLE
Provide divider text

### ISSUE THREAD

**Issue by nburns-tausight** [wojtekmaj/react-daterange-picker#47]
So far this has proven to be a very nice package.  One issue I have is the design we are working with requires us to have [start date] to [end date] where this package only uses "–".  Im not familiar with overriding an npm package and thus asking here if its possible to get a prop of "divider" which can take a string or jsx element to be used in place of the default?

Thanks

**Comment by wojtekmaj** [comment]
I love this idea :) Implementing this right now.
