### ISSUE TITLE
getting date in string without timeZone

### ISSUE THREAD

**Issue by HarshilSolanki** [wojtekmaj/react-daterange-picker#50]
Hii, i m used used this package and working properly but i was required only date and time but Timezone is bot require, so can you give me datetime string feature without timezone?? i was send the screen shot, what exactly getting from output when i was using dateRange
Example: "Fri Dec 20 2019 00:00:00 GMT+0530 (India Standard Time)" ==> Getting this string
and what i was need from you
Example: "Fri Dec 20 2019 00:00:00 GMT+0530"
can you give me that type return value ??

**Comment by wojtekmaj** [comment]
What you're looking at is a human readable representation of Date() object, done by your browser. It's not a string.

React-DateRange-Picker does not add any timezones on its own - it simply uses the local one.

Try `console.log(new Date())` in your browser.
