### ISSUE TITLE
changing the date format

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [wojtekmaj/react-daterange-picker#52]
Hi @wojtekmaj ,
thanks for the package,
I have implemented the react-daterange-picker, but i want to get the value in format "dd-mm-yyyy",
but it was not working,
below is my code,

```

import React, { Component } from 'react';
import DateRangePicker from '@wojtekmaj/react-daterange-picker';

class MyApp extends Component {
  state = {
    date: [new Date(), new Date()],
  }

   render() {
console.log(this.state.date);
    return (
      <div>
        <DateRangePicker
          onChange={value => {
                      this.setState({ date: value });
                    }}
          value={this.state.date}
          format="dd-mm-yyyy"
        />
      </div>
    );
  }
}
```

shows in format `[Tue Jan 07 2020 10:55:20 GMT+0800 (Philippine Standard Time), Tue Jan 07 2020 10:55:20 GMT+0800 (Philippine Standard Time)]`

but Expected `[07-01-2020, 07-01-2020]`

**Comment by wojtekmaj** [comment]
`format` only changes date format displayed on the picker. Regardless of the format chosen, onChange will be given [`Date` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). You'll never get a string returned.

**Comment by AmritPhalake** [comment]
How to rename weekdays from 'Mon','Tue','Wed'.... to 'M','T','W',...
