### ISSUE TITLE
Manually inputting a leading zero causes the month/day to have 3 digits

### ISSUE THREAD

**Issue by pbarnum** [wojtekmaj/react-daterange-picker#54]
When I manually type in the date (month/day) I typically enter in the leading zero if the month/day is < 10. However, the date-picker will still add it's own "leading" zero and I am left with 3 digits for the month/day.

This currently can be seen in the online demo.

<img width="372" alt="Screen Shot 2020-02-17 at 10 48 57 AM" src="https://user-images.githubusercontent.com/6970266/74679665-5d804e00-5173-11ea-86ab-41fd5fb339b4.png">

**Comment by dmluzhin** [comment]
I have the same problem

**Comment by MichelGeorgy** [comment]
Me too running v8.0.5

**Comment by Sowmyashree-P** [comment]
same problem

**Comment by wojtekmaj** [comment]
Fixed in v3.1.0.
