### ISSUE TITLE
Range divider not working

### ISSUE THREAD

**Issue by MatiasManevi** [wojtekmaj/react-daterange-picker#55]
The rangeDivider attribute does not change anything when passing a string like "  to  " for example.

This is my package.json dependencies

`` "dependencies": {
    "@material-ui/core": "^4.9.0",
    "@material-ui/icons": "^4.9.0",
    "@material-ui/styles": "^4.9.0",
    "@wojtekmaj/react-daterange-picker": "^2.5.0",
    "axios": "^0.19.0",
    "material-table": "^1.50.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-google-login": "^5.0.4",
    "react-router-dom": "^5.0.0"
  }, ``

[Here](https://codesandbox.io/s/zealous-yalow-bb2wh) is a demo with the error.

**Comment by wojtekmaj** [comment]
`rangeDivider` support was added in v3.0.0.
