### ISSUE TITLE
Daterange shows one month ahead in the picker

### ISSUE THREAD

**Issue by kevallakhani** [wojtekmaj/react-daterange-picker#57]
code: 
```
this.state.date = [newDate(2020,1,5), new Date(2020,2,5)];
```

But in the DateRange picker on frontEnd it shows `2020/02/05 - 2020/03/05`
Moves one month ahead for start date and end date.

**Comment by wojtekmaj** [comment]
In JavaScript, months are from 0-11. Yeah, I feel you mate.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
