### ISSUE TITLE
Problem with the import of the module

### ISSUE THREAD

**Issue by tvcologan** [wojtekmaj/react-daterange-picker#6]
Hi,

I am trying to use the date range picker, but upon import, it displays the message of module not found:

`./src/components/MyComponent.js
Module not found: Can't resolve 'react-daterange-picker' in '/MyAppPath/components'`

I have checked the node_modules directory and the 'react-daterange-picker' folder is there. And I have restarted node, re-installed everything but the error keeps appearing.

Am I missing something? Can anyone help me?

Thanks!

**Comment by wojtekmaj** [comment]
react-daterange-picker is not published on npm yet. Check [tl;dr](https://github.com/wojtekmaj/react-daterange-picker#tldr) section in README.

**Comment by tvcologan** [comment]
Thanks for the quick response, but I had read that section, and when I try to run the `npm run build` command, the same error gets displayed and the execution of the command stops with an error.

**Comment by wojtekmaj** [comment]
Are you running `npm run build` in package's directory, or your own? Because what you need to build is the package, not your project.

**Comment by tvcologan** [comment]
Ok, my bad. Thanks!!
