### ISSUE TITLE
Min/Max Date Issue

### ISSUE THREAD

**Issue by Bilal-Abbas** [wojtekmaj/react-daterange-picker#63]
Min date issue.

I have simply added your package with non-other customization but the user can easily select any date.

```
class DateRangeInput extends Component {
  state = {
    date: [new Date(), new Date()]
  };

  onChange = date => this.setState({ date });

  render() {
    const { className, placeholder } = this.props;
    return (
      <div>
        <DateRangePicker onChange={this.onChange} value={this.state.date} />
      </div>
    );
  }
}
```

![daterange picker](https://user-images.githubusercontent.com/40523465/78023222-ba287880-736f-11ea-96b7-1b1f653ba9d4.png)

**Comment by Bilal-Abbas** [comment]
Any help ?

**Comment by wojtekmaj** [comment]
[README](https://github.com/wojtekmaj/react-daterange-picker/blob/master/README.md), look for minDate, maxDate.
