### ISSUE TITLE
Prop 'showDoubleView' not working

### ISSUE THREAD

**Issue by telekommander** [wojtekmaj/react-daterange-picker#65]
Hello,

is there a bug or maybe I using the react-date-rangepicker in a wrong way ?

The prop `showDoubleView` is taken from the `react-calender` and should show 2 month 
in `react-date-rangepicker`, if I read this here correctly. But it seems it is not working.

```
<DateRangePicker
    showDoubleView
/>
```

Here ist a simple example @ [https://codesandbox.io/s/thirsty-rubin-ldt4z](https://codesandbox.io/s/thirsty-rubin-ldt4z)

According documentation, i use the following packages:
```
    @wojtekmaj/react-daterange-picker": "2.5.0
    react-calendar": "^3.0.1
```

Thank you!

**Comment by wojtekmaj** [comment]
Actuallly, the newest released React-DateRange-Picker is still using React-Calendar from 3.x branch :( It's on master at the moment.

Keeping [breaking changes](https://github.com/wojtekmaj/react-calendar/releases/tag/v3.0.0) in mind, you can force React-Calendar to v3.x using [Yarn selective dependency resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) and give it a go.

Or wait for React-DateRange-Picker 3.x release.

**Comment by wojtekmaj** [comment]
Actually, enjoy, just published a v3.x :)

**Comment by telekommander** [comment]
Great! Thank you!
