### ISSUE TITLE
Error "Unable to resolve path" when trying to use the package

### ISSUE THREAD

**Issue by emmyhayer** [wojtekmaj/react-daterange-picker#7]
./src/components/organismes/AddItemForm/AddItemForm.js
  Line 5:  Unable to resolve path to module 'react-daterange-picker'  import/no-unresolved

i installed both yarn and npm but getting this error..but package is showing in node_modules folder

i tried this on two projects, getting same error

**Comment by wojtekmaj** [comment]
Hello,
React-DateRange-Picker is not on npm due to name conflict. You need to build it yourself if you would like to use it.

**Comment by cryptoclimate** [comment]
I tried to build it but am getting this error:

```
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 46068 packages in 4.063s
found 4 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm run build

> react-daterange-picker@1.0.0 build node_modules/react-daterange-picker
> yarn run build-js && yarn run copy-styles && yarn run build-styles

yarn run v1.9.4
$ babel src -d dist --ignore __tests__
SyntaxError: src/DateRangePicker.jsx: Unexpected token (22:8)
  20 |   }
  21 | 
> 22 |   state = {};
     |         ^
  23 | 
  24 |   componentDidMount() {
  25 |     document.addEventListener('mousedown', this.onClick);
error Command failed with exit code 1.
```

**Comment by wojtekmaj** [comment]
Uh... I may release it under @wojtekmaj/react-daterange-picker ;) I think that would settle it.

**Comment by wojtekmaj** [comment]
@cryptoclimate @emmyhayer The package is now published as a scoped package under `@wojtekmaj/react-daterange-picker` name. Please check it out; it comes with prebuilt code, so you shouldn't have any more problems with it!
