### ISSUE TITLE
how get date ranges from onchange event

### ISSUE THREAD

**Issue by harunpandianjb** [wojtekmaj/react-daterange-picker#72]
i need to get range values from daterange picker .how to use onchange can explain with code

**Comment by stivmartinez** [comment]
@harunpandianjb the output are an state array, then you could access to each value with something like that:
`value[0]` for the start date and `value[1]` for the end date.
Hope this could help you.

**Comment by wojtekmaj** [comment]
onChange returns an array like this: [startDate, endDate].
