### ISSUE TITLE
'@wojtekmaj/react-daterange-picker@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by A-tibrewal** [wojtekmaj/react-daterange-picker#74]
while installing with `npm i @wojtekmaj/react-daterange-picker` I am getting this error 
<img width="1150" alt="Screenshot 2020-08-06 at 4 48 46 PM" src="https://user-images.githubusercontent.com/9450758/89525997-b36dae80-d804-11ea-8b09-1f77fcd28db6.png">

**Comment by wojtekmaj** [comment]
npm outage
