### ISSUE TITLE
Highlight current day in the calendar view.

### ISSUE THREAD

**Issue by eenewbsauce** [wojtekmaj/react-daterange-picker#75]
I hope this isn't a duplicate. I looked through all existing issues and couldn't seem to find a match.

I'd like a `prop` to highlight the current day. It would be a nice UX improvement.

I'd be happy to do the work, if you could steer me in the right direction.

**Comment by wojtekmaj** [comment]
v3.0.0 includes React-Calendar v3.0.0, which has current day highlighted by default.

You can also use tileClassName to pass your own class names to specific tiles:

https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-style-tiles

**Comment by eenewbsauce** [comment]
Thank you very much! The css class is `.react-calendar__tile--now` for future reference.
