### ISSUE TITLE
is it possible to force selection of a start range on the left calendar and the end on the right in 2 calendars view?

### ISSUE THREAD

**Issue by vtarelkin** [wojtekmaj/react-daterange-picker#79]
good day.

@wojtekmaj 
I use prop 'showDoubleView' and I need to select the start of the range on the left calendar and the end of the range on the right calendar. Now it is possible to select both dates on the left calendar. Could that be fixed? Thank you

**Comment by wojtekmaj** [comment]
No, it's not possible. Sorry.
