### ISSUE TITLE
Input Issue when set maxDetail='decade'

### ISSUE THREAD

**Issue by hoangvuong-689cloud** [wojtekmaj/react-daterange-picker#80]
When I set maxDetail is **_decade_** and input(by keyboard, not select) year with the format **_yyyy_**, the error occurs:
`Cannot read property '0' of null
at DateInput.get (DateInput.js:556)
at DateInput.js:237`

Could you help to take a look? Thanks

**Comment by wojtekmaj** [comment]
Fixed in [react-date-picker v8.0.6](https://github.com/wojtekmaj/react-date-picker/releases/tag/v8.0.6).
