### ISSUE TITLE
Global style in overriting my own style

### ISSUE THREAD

**Issue by Luiyit** [wojtekmaj/react-daterange-picker#84]
Hi, Thanks for the component. It works fine for me. I just have an issue with the global style.
As you use !important in your rules, this is overwrting the style of other components and is so hard to fix it on my end because you are using `!important`. So, I think a simple solution would be add a custom class name to your main wrap component, something like that:

`<div className="react-date-range-calendar row" style={{ maxWidth: "100%" }}>`

and use this class to create a wrap in the style too

```
.react-date-range-calendar{ 
      *{
        border: none !important;
      }
      .card {
          background: white !important;
          background-color: white !important;
      }
      .right{
          margin-left:0px;    padding-left:0px;
      }
      .hide {
          display: none;
      }
      .__cal__{
          max-width: 400px;
          min-width: 400px;
      }
    }
  }
```

Do you have any idea to prevent this issue without change the code?
Thanks!

**Comment by wojtekmaj** [comment]
Uhhhh, I can't find any `!important` in our styles 🧐 

Anyway, the easiest way to avoid any styling conflicts would be to import React-DateRange-Picker without the styles ([README](../) <kbd>Ctrl</kbd>+<kbd>F</kbd> nostyle) and build upon them in your own project

**Comment by Luiyit** [comment]
> Uhhhh, I can't find any `!important` in our styles 🧐
> 
> Anyway, the easiest way to avoid any styling conflicts would be to import React-DateRange-Picker without the styles ([README](../) Ctrl+F nostyle) and build upon them in your own project

Thanks for your response. I will take a look. nostyle work for me.
