### ISSUE TITLE
Open calendar only on icon click and not on focus of input

### ISSUE THREAD

**Issue by Sowmyashree-P** [wojtekmaj/react-daterange-picker#86]
Is it possible to customize so that on focus of input user can only type the date values and on clicking of calendar icon opens calendar and user is able to select the dates

**Comment by jasontk19** [comment]
+1 this is something we'd also like to be able to do

**Comment by wojtekmaj** [comment]
Will be fixed by #95.

By default, the old behavior will be still present so that we don't introduce a breaking change.

In the next breaking version, the default setting will be to NOT open calendar on input focus to be more in line with native date pickers.
