### ISSUE TITLE
The closeCalendar prop doesn't work as specified in the documentation

### ISSUE THREAD

**Issue by goramaciej** [wojtekmaj/react-daterange-picker#87]
whether I set closeCalendar prop to true or false, the calendar closes after select the end date

**Comment by AymanMorsy** [comment]
+1

**Comment by A-tibrewal** [comment]
+1

**Comment by jasontk19** [comment]
+1 we would also like to try this option but it's not working currently.

**Comment by tonirilix** [comment]
It seems there's one PR for this issue https://github.com/wojtekmaj/react-daterange-picker/pull/93#issue-631384118

**Comment by irondimk** [comment]
+1, the solution is described earlier, but the problem is still relevant.
