### ISSUE TITLE
react-daterange-picker doesn't work when using vite

### ISSUE THREAD

**Issue by jaknas** [wojtekmaj/react-daterange-picker#88]
The error is: `Uncaught ReferenceError: require is not defined`

See: https://github.com/vitejs/vite/issues/986 and https://github.com/vitejs/vite/issues/343#issuecomment-638318444

**Comment by kleyu** [comment]
update:
works fine if using entry without styles and loading them alongside inside the component:
```
import '@wojtekmaj/react-daterange-picker/dist/DateRangePicker.css';
import 'react-calendar/dist/Calendar.css';
import DateRangePicker from '@wojtekmaj/react-daterange-picker/dist/entry.nostyle';
```

**Comment by young666** [comment]
You could also use this plugin as in this example: https://github.com/vitejs/vite/issues/5308#issuecomment-1010652389
