### ISSUE TITLE
Request to add search icon for date rage picker

### ISSUE THREAD

**Issue by bishaludash** [wojtekmaj/react-daterange-picker#90]
Hi, First of all I would like to thank you for making this beautiful package , secondly I would like to request to add a search icon prop just like calander prop. Right now i can select the date range and would like to execute a function on clicking that search icon. If there is a workaround this please do tell.

![Screenshot from 2021-03-16 11-23-26](https://user-images.githubusercontent.com/24315018/111261329-69766200-864a-11eb-8ea1-16253ef2f2e1.png)

```
import DateRangePicker from "@wojtekmaj/react-daterange-picker";
const [date, setDate] = useState(["", ""]);

<DateRangePicker
          name="date"
          onChange={setDate}
          onKeyPress={filterClient}
          value={date}
          calendarIcon={null}
/>
```

**Comment by wojtekmaj** [comment]
Sounds like you need to wrap DateRangePicker in another component, that would render DateRangePicker and your Search button.
