### ISSUE TITLE
Unable to use react-daterange-picker

### ISSUE THREAD

**Issue by KrisBhatt** [wojtekmaj/react-daterange-picker#91]
Hi,

I have followed the simple instruction for installing the package. After installing getting error:

/node_modules/@wojtekmaj/react-daterange-picker/node_modules/react-calendar/dist/Calendar.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\@wojtekmaj\react-daterange-picker\dist\entry.js

**Project Description**:
React Version: 16.13

To resolve this issue I have tried to install react-calendar but issue is still not resolved. Any help on this would be nice !

**Comment by Frontend-io** [comment]
I presume you're using NextJs. NextJS framework doesn't allow CSS import anywhere else except from the _app file. I don't know if there's a way around this for this library, maybe let us import CSS separately for NextJS users. 

cc @wojtekmaj

**Comment by wojtekmaj** [comment]
You can already do this, please read README
