### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by hckhanh** [wojtekmaj/react-daterange-picker#96]
I wonder why react-date-picker and react-datetimerange-picker have their own ts supports, but not this one.

**Comment by GreenRidingHood** [comment]
Is there any news about typescript support, thanks

**Comment by wojtekmaj** [comment]
Type definitions are to be added to DefinitelyTyped project. PRs with type definitions added directly to here won't be accepted.

**Comment by GreenRidingHood** [comment]
@hckhanh  i solved issue with create `decs.d.ts` file in project and src file , i am not sure which one i need but i created both places

content of my `src/decs.d.s` file is

`declare module "@wojtekmaj/react-daterange-picker";`
`declare module "react-calendar";`
`declare module "react-moment";`
`declare module "react-dates/initialize";`


proj  file `decs.d.ts` content 

`/* eslint-disable */`
`declare module "@wojtekmaj/react-daterange-picker";`
`declare module "react-daterange-picker";`


and my state hook

`const [visitData, setVisitData] = useState({
		dateRange: [new Date(), new Date()],
		resource: "",
	});`

hope works for you as well, best

**Comment by hckhanh** [comment]
@GreenRidingHood  perhaps we should have a PR for this :D

**Comment by rohmanhm** [comment]
They have typescript support here https://www.npmjs.com/package/@types/wojtekmaj__react-daterange-picker

```bash
npm i -D @types/wojtekmaj__react-daterange-picker
```

**Comment by wojtekmaj** [comment]
Implemented in #271.
