### ISSUE TITLE
Can't load Range picker. Style not loading.

### ISSUE THREAD

**Issue by savageqm** [wojtekmaj/react-daterange-picker#97]
I currently can't get the Range picker to load properly. It seems like the style is not being assigned correctly.

This is what I see when I load my react component.
![image](https://user-images.githubusercontent.com/4581881/124137518-bf351580-da53-11eb-86b4-011e4209b9e8.png)

My react component is set up like this:
`import DateRangePicker from '@wojtekmaj/react-daterange-picker';`
`import '@wojtekmaj/react-daterange-picker/dist/DateRangePicker.css';`

          <div>
                <DateRangePicker
                    onChange={onChange}
                    value={value}
                />
            </div>

in my webpack under module rules I have to just include the module for this range picker.
` exclude: /node_modules\/(?!(react-daterange-picker)\/).*/,`

any tips?

**Comment by KorNatalya** [comment]
@savageqm you should add styles to angular.json
