### ISSUE TITLE
Ability to stop/override calendar closing on outside click?

### ISSUE THREAD

**Issue by joshcawthorne** [wojtekmaj/react-daterange-picker#99]
Hi,

I'm looking for a way to keep the calendar always visible, both after date range select, and immaterial of if there's a click outside of the calendar. Is this possible? I currently have it open by default & not closing on date select, but I don't seem to be able to find a way to overwrite the method that closes it on outside click.

Thanks!

**Comment by dhirajsharma17** [comment]
+1. would be a nice feature to control outside click and when to close the calendar

**Comment by dhirajsharma17** [comment]
+1
